[package]
name = "fast_search"
version = "0.1.0"
authors = ["brian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1.3"